### ISSUE TITLE
Move templates inside the Hatstall application

### ISSUE THREAD

**Issue by jjmerchante** [chaoss/grimoirelab-hatstall#100]
Django templates are in 2 directories: `django-hatstall/templates` and `hatstall/templates`. When I try to reuse the application (`hatstall` directory), I cannot use the templates because it depends on `base.html` that is inside `django-hatstall` and it is not included in the package.

I propose to move the templates from `django-hatstall` to `hatstall`. I make the changes, but I wanted to know if you have a better way to do it.

Thank you

**Comment by valeriocos** [comment]
@mafesan @dlumbrer I see that you are the last ones that modified those folders. Could you share your thoughts about @jjmerchante's proposal? Thanks (cc @sduenas)

**Comment by dlumbrer** [comment]
> @mafesan @dlumbrer I see that you are the last ones that modified those folders. Could you share your thoughts about @jjmerchante's proposal? Thanks (cc @sduenas)

Hi folks! If I'm right, the idea of having this structure was thought in order to have more than one Django app inside the same project. 

I think that currently we are not going to follow this structure, so for me there is no problem. We have to take into account that the changes may modify the docker image creation process and the way of deploy hatstall.

**Comment by valeriocos** [comment]
Thanks for the info @dlumbrer. @mafesan @sduenas please share your thoughts, thanks

**Comment by sduenas** [comment]
Taking account what @dlumbrer said above I think there's no problem to do it. Please take into account how the docker image is build.
