### ISSUE TITLE
Can not assign same organization in two different time frames

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-hatstall#108]
Something is wrong with the affiliation ranges when the same organization is being assigned in two different time ranges. When you try to assign the second one, the change is lost.

Have a look at the example. This user is affiliated to two different organizations:
![image](https://user-images.githubusercontent.com/326719/86826014-6a54fe00-c090-11ea-8cd8-d7119581f263.png)

So I want to add a new affiliation because our contributor came back to "Universidad Rey Juan Carlos". I tried with March 31st as the ending date and I got the same result.
![image](https://user-images.githubusercontent.com/326719/86826079-822c8200-c090-11ea-9f07-830289d80d9a.png)
I click on "Update" (in the new row) and this is what I get:
![image](https://user-images.githubusercontent.com/326719/86826104-8eb0da80-c090-11ea-821c-d92f5b052ba9.png)

I've seen this behavior in the version currently deployed on biterg.io

**Comment by mafesan** [comment]
I was able to replicate this bug with both Hatstall and Sortinghat's last versions (at the moment, `0.2.3` and `0.7.14` respectively).

This is happening because the method in charge of updating the dates from enrollments `update_enrollment`, first deletes the enrollment with the old dates and then creates a new one with the new dates.

When an enrollment is first added, Hatstall does it using the default min and max dates. This means when that enrollment is set to be updated, is deleted in Sortinghat, deleting also other enrollments for that organization with other date ranges (if any) which are always included into the default one.

For instance, let's build this scenario on Hatstall from scratch:
* Add `Org 1`.
* New enrollment `enr1` to `Org 1`. This is added with default dates, from `1900-01-01` to `2100-01-01`.
* Enrollment `enr1` start date is updated to `2019-01-01`.
* New enrollment `enr2` to `Org 1`. This is also added with default dates, from `1900-01-01` to `2100-01-01`.
* Enrollment `enr2` end date is set to `2012-05-30`.

Then, the `update_enrollment` method (Hatstall) first deletes the enrollment `enr2` with the old dates (1900 - 2100), so it also deletes `enr1`, as its date range (2019 - 2100) is under the bigger one.

I'm submitting the fix for this issue. I followed this approach:

* First, save a copy of the existing enrollments for the given organization before modifying the state of the registry.
* Delete the enrollment with old dates.
* Add an enrollment with the new dates.
* If there is an error when adding the the new dates, restore the initial state by adding again the enrollment with the former date range.
* In case other enrollments from the given organization were deleted (because they had a date range included within the deleted one), they are also restored.

Note: the method is not checking if there are overlapping date ranges.

**Comment by sduenas** [comment]
@mafesan why doesn't it work using [merge command](https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/cmd/enroll.py)

**Comment by mafesan** [comment]
> @mafesan why doesn't it work using [enroll command](https://github.com/chaoss/grimoirelab-sortinghat/blob/master/sortinghat/cmd/enroll.py) which can merge ranges if needed?

Thanks for the suggestion @sduenas , the PR (https://github.com/chaoss/grimoirelab-hatstall/pull/111) is now ready for review including the proposed changes.
